// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: polygon/greetings.proto

package stream

import (
	context "context"
	constants "github.com/bhbosman/gocommon/constants"
	stream "github.com/bhbosman/gocommon/stream"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	proto1 "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// https://polygon.io/sockets for forex
type PolygonMessageReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType string `protobuf:"bytes,1,opt,name=EventType,json=ev,proto3" json:"EventType,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
}

func (x *PolygonMessageReceived) Reset() {
	*x = PolygonMessageReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polygon_greetings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonMessageReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonMessageReceived) ProtoMessage() {}

func (x *PolygonMessageReceived) ProtoReflect() protoreflect.Message {
	mi := &file_polygon_greetings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonMessageReceived.ProtoReflect.Descriptor instead.
func (*PolygonMessageReceived) Descriptor() ([]byte, []int) {
	return file_polygon_greetings_proto_rawDescGZIP(), []int{0}
}

func (x *PolygonMessageReceived) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PolygonMessageReceived) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PolygonMessageReceived) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (self *PolygonMessageReceived) TypeCode() uint32 {
	return PolygonMessageReceivedTypeCode
}

type PolygonMessageSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action string `protobuf:"bytes,1,opt,name=Action,json=action,proto3" json:"Action,omitempty"`
	Params string `protobuf:"bytes,2,opt,name=Params,json=params,proto3" json:"Params,omitempty"`
}

func (x *PolygonMessageSend) Reset() {
	*x = PolygonMessageSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polygon_greetings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonMessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonMessageSend) ProtoMessage() {}

func (x *PolygonMessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_polygon_greetings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonMessageSend.ProtoReflect.Descriptor instead.
func (*PolygonMessageSend) Descriptor() ([]byte, []int) {
	return file_polygon_greetings_proto_rawDescGZIP(), []int{1}
}

func (x *PolygonMessageSend) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolygonMessageSend) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (self *PolygonMessageSend) TypeCode() uint32 {
	return PolygonMessageSendTypeCode
}

var File_polygon_greetings_proto protoreflect.FileDescriptor

var file_polygon_greetings_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x61, 0x0a, 0x16, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x65, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x44, 0x0a, 0x12, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polygon_greetings_proto_rawDescOnce sync.Once
	file_polygon_greetings_proto_rawDescData = file_polygon_greetings_proto_rawDesc
)

func file_polygon_greetings_proto_rawDescGZIP() []byte {
	file_polygon_greetings_proto_rawDescOnce.Do(func() {
		file_polygon_greetings_proto_rawDescData = protoimpl.X.CompressGZIP(file_polygon_greetings_proto_rawDescData)
	})
	return file_polygon_greetings_proto_rawDescData
}

var file_polygon_greetings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polygon_greetings_proto_goTypes = []interface{}{
	(*PolygonMessageReceived)(nil), // 0: golang.example.policy.PolygonMessageReceived
	(*PolygonMessageSend)(nil),     // 1: golang.example.policy.PolygonMessageSend
}
var file_polygon_greetings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_polygon_greetings_proto_init() }
func file_polygon_greetings_proto_init() {
	if File_polygon_greetings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_polygon_greetings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonMessageReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polygon_greetings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonMessageSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polygon_greetings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polygon_greetings_proto_goTypes,
		DependencyIndexes: file_polygon_greetings_proto_depIdxs,
		MessageInfos:      file_polygon_greetings_proto_msgTypes,
	}.Build()
	File_polygon_greetings_proto = out.File
	file_polygon_greetings_proto_rawDesc = nil
	file_polygon_greetings_proto_goTypes = nil
	file_polygon_greetings_proto_depIdxs = nil
}

const PolygonMessageReceivedTypeCode uint32 = 764086940
const PolygonMessageSendTypeCode uint32 = 2766463228

//true
//true
//false
//false
type PolygonMessageReceivedWrapper struct {
	stream.BaseMessageWrapper
	Data *PolygonMessageReceived
}

func (self *PolygonMessageReceivedWrapper) Message() proto1.Message {
	return self.Data
}

func (self *PolygonMessageReceivedWrapper) messageWrapper() stream.IMessageWrapper {
	return self
}

func NewPolygonMessageReceivedWrapper(
	cancelCtx context.Context,
	cancelFunc context.CancelFunc,
	toReactor stream.ToReactorFunc,
	toConnection stream.ToConnectionFunc,
	data *PolygonMessageReceived) *PolygonMessageReceivedWrapper {
	return &PolygonMessageReceivedWrapper{
		BaseMessageWrapper: stream.NewBaseMessageWrapper(
			cancelCtx,
			cancelFunc,
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	PolygonMessageReceivedTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto1.Message {
			return &PolygonMessageReceived{}
		},
		CreateWrapper: func(
			cancelCtx context.Context,
			cancelFunc context.CancelFunc,
			toReactor stream.ToReactorFunc,
			toConnection stream.ToConnectionFunc,
			data proto1.Message) (stream.IMessageWrapper, error) {
			if msg, ok := data.(*PolygonMessageReceived); ok {
				return NewPolygonMessageReceivedWrapper(
					cancelCtx,
					cancelFunc,
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, constants.InvalidParam
		}})

//true
//true
//false
//false
type PolygonMessageSendWrapper struct {
	stream.BaseMessageWrapper
	Data *PolygonMessageSend
}

func (self *PolygonMessageSendWrapper) Message() proto1.Message {
	return self.Data
}

func (self *PolygonMessageSendWrapper) messageWrapper() stream.IMessageWrapper {
	return self
}

func NewPolygonMessageSendWrapper(
	cancelCtx context.Context,
	cancelFunc context.CancelFunc,
	toReactor stream.ToReactorFunc,
	toConnection stream.ToConnectionFunc,
	data *PolygonMessageSend) *PolygonMessageSendWrapper {
	return &PolygonMessageSendWrapper{
		BaseMessageWrapper: stream.NewBaseMessageWrapper(
			cancelCtx,
			cancelFunc,
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	PolygonMessageSendTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto1.Message {
			return &PolygonMessageSend{}
		},
		CreateWrapper: func(
			cancelCtx context.Context,
			cancelFunc context.CancelFunc,
			toReactor stream.ToReactorFunc,
			toConnection stream.ToConnectionFunc,
			data proto1.Message) (stream.IMessageWrapper, error) {
			if msg, ok := data.(*PolygonMessageSend); ok {
				return NewPolygonMessageSendWrapper(
					cancelCtx,
					cancelFunc,
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, constants.InvalidParam
		}})
