// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.10
// 	protoc        v3.14.0
// source: marketData/marketData.proto

package stream

import (
	stream "github.com/bhbosman/gocommon/stream"
	goerrors "github.com/bhbosman/goerrors"
	goprotoextra "github.com/bhbosman/goprotoextra"
	v2 "github.com/reactivex/rxgo/v2"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  float64 `protobuf:"fixed64,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Volume float64 `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_marketData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_marketData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_marketData_marketData_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Point) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (self *Point) TypeCode() uint32 {
	return PointTypeCode
}

type PublishTop5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instrument         string   `protobuf:"bytes,1,opt,name=Instrument,proto3" json:"Instrument,omitempty"`
	Spread             float64  `protobuf:"fixed64,2,opt,name=Spread,proto3" json:"Spread,omitempty"`
	SourceTimeStamp    int64    `protobuf:"varint,3,opt,name=SourceTimeStamp,proto3" json:"SourceTimeStamp,omitempty"`
	SourceMessageCount int64    `protobuf:"varint,4,opt,name=SourceMessageCount,proto3" json:"SourceMessageCount,omitempty"`
	UpdateCount        int64    `protobuf:"varint,5,opt,name=UpdateCount,proto3" json:"UpdateCount,omitempty"`
	Bid                []*Point `protobuf:"bytes,6,rep,name=Bid,proto3" json:"Bid,omitempty"`
	Ask                []*Point `protobuf:"bytes,7,rep,name=Ask,proto3" json:"Ask,omitempty"`
	Source             string   `protobuf:"bytes,8,opt,name=Source,proto3" json:"Source,omitempty"`
	UniqueName         string   `protobuf:"bytes,9,opt,name=UniqueName,proto3" json:"UniqueName,omitempty"`
}

func (x *PublishTop5) Reset() {
	*x = PublishTop5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_marketData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishTop5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTop5) ProtoMessage() {}

func (x *PublishTop5) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_marketData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTop5.ProtoReflect.Descriptor instead.
func (*PublishTop5) Descriptor() ([]byte, []int) {
	return file_marketData_marketData_proto_rawDescGZIP(), []int{1}
}

func (x *PublishTop5) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *PublishTop5) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *PublishTop5) GetSourceTimeStamp() int64 {
	if x != nil {
		return x.SourceTimeStamp
	}
	return 0
}

func (x *PublishTop5) GetSourceMessageCount() int64 {
	if x != nil {
		return x.SourceMessageCount
	}
	return 0
}

func (x *PublishTop5) GetUpdateCount() int64 {
	if x != nil {
		return x.UpdateCount
	}
	return 0
}

func (x *PublishTop5) GetBid() []*Point {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *PublishTop5) GetAsk() []*Point {
	if x != nil {
		return x.Ask
	}
	return nil
}

func (x *PublishTop5) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PublishTop5) GetUniqueName() string {
	if x != nil {
		return x.UniqueName
	}
	return ""
}

func (self *PublishTop5) TypeCode() uint32 {
	return PublishTop5TypeCode
}

type FullMarketDataRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instrument string `protobuf:"bytes,1,opt,name=Instrument,proto3" json:"Instrument,omitempty"`
}

func (x *FullMarketDataRegister) Reset() {
	*x = FullMarketDataRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_marketData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullMarketDataRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMarketDataRegister) ProtoMessage() {}

func (x *FullMarketDataRegister) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_marketData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMarketDataRegister.ProtoReflect.Descriptor instead.
func (*FullMarketDataRegister) Descriptor() ([]byte, []int) {
	return file_marketData_marketData_proto_rawDescGZIP(), []int{2}
}

func (x *FullMarketDataRegister) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (self *FullMarketDataRegister) TypeCode() uint32 {
	return FullMarketDataRegisterTypeCode
}

type FullMarketDataUnRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instrument string `protobuf:"bytes,1,opt,name=Instrument,proto3" json:"Instrument,omitempty"`
}

func (x *FullMarketDataUnRegister) Reset() {
	*x = FullMarketDataUnRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_marketData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullMarketDataUnRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMarketDataUnRegister) ProtoMessage() {}

func (x *FullMarketDataUnRegister) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_marketData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMarketDataUnRegister.ProtoReflect.Descriptor instead.
func (*FullMarketDataUnRegister) Descriptor() ([]byte, []int) {
	return file_marketData_marketData_proto_rawDescGZIP(), []int{3}
}

func (x *FullMarketDataUnRegister) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (self *FullMarketDataUnRegister) TypeCode() uint32 {
	return FullMarketDataUnRegisterTypeCode
}

var File_marketData_marketData_proto protoreflect.FileDescriptor

var file_marketData_marketData_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x22, 0xad, 0x02, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f, 0x70,
	0x35, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x53, 0x70, 0x72, 0x65, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x42, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x41, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x38, 0x0a, 0x16, 0x46, 0x75, 0x6c, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x49,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x18, 0x46,
	0x75, 0x6c, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x49, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketData_marketData_proto_rawDescOnce sync.Once
	file_marketData_marketData_proto_rawDescData = file_marketData_marketData_proto_rawDesc
)

func file_marketData_marketData_proto_rawDescGZIP() []byte {
	file_marketData_marketData_proto_rawDescOnce.Do(func() {
		file_marketData_marketData_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketData_marketData_proto_rawDescData)
	})
	return file_marketData_marketData_proto_rawDescData
}

var file_marketData_marketData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketData_marketData_proto_goTypes = []interface{}{
	(*Point)(nil),                    // 0: Point
	(*PublishTop5)(nil),              // 1: PublishTop5
	(*FullMarketDataRegister)(nil),   // 2: FullMarketDataRegister
	(*FullMarketDataUnRegister)(nil), // 3: FullMarketDataUnRegister
}
var file_marketData_marketData_proto_depIdxs = []int32{
	0, // 0: PublishTop5.Bid:type_name -> Point
	0, // 1: PublishTop5.Ask:type_name -> Point
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_marketData_marketData_proto_init() }
func file_marketData_marketData_proto_init() {
	if File_marketData_marketData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketData_marketData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_marketData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishTop5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_marketData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullMarketDataRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_marketData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullMarketDataUnRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketData_marketData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketData_marketData_proto_goTypes,
		DependencyIndexes: file_marketData_marketData_proto_depIdxs,
		MessageInfos:      file_marketData_marketData_proto_msgTypes,
	}.Build()
	File_marketData_marketData_proto = out.File
	file_marketData_marketData_proto_rawDesc = nil
	file_marketData_marketData_proto_goTypes = nil
	file_marketData_marketData_proto_depIdxs = nil
}

// Typecode generated from: "Point"
const PointTypeCode uint32 = 1986321440

// Typecode generated from: "PublishTop5"
const PublishTop5TypeCode uint32 = 2990202154

// Typecode generated from: "FullMarketDataRegister"
const FullMarketDataRegisterTypeCode uint32 = 477977412

// Typecode generated from: "FullMarketDataUnRegister"
const FullMarketDataUnRegisterTypeCode uint32 = 2486720139

//true
//true
//false
//false
type PointWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *Point
}

func (self *PointWrapper) Message() interface{} {
	return self.Data
}

func (self *PointWrapper) messageWrapper() interface{} {
	return self
}

func NewPointWrapper(
	toReactor v2.NextFunc,
	toConnection v2.NextFunc,
	data *Point) *PointWrapper {
	return &PointWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	PointTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &Point{}
		},
		CreateWrapper: func(
			toReactor v2.NextFunc,
			toConnection v2.NextFunc,
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*Point); ok {
				return NewPointWrapper(
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})

//true
//true
//false
//false
type PublishTop5Wrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *PublishTop5
}

func (self *PublishTop5Wrapper) Message() interface{} {
	return self.Data
}

func (self *PublishTop5Wrapper) messageWrapper() interface{} {
	return self
}

func NewPublishTop5Wrapper(
	toReactor v2.NextFunc,
	toConnection v2.NextFunc,
	data *PublishTop5) *PublishTop5Wrapper {
	return &PublishTop5Wrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	PublishTop5TypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &PublishTop5{}
		},
		CreateWrapper: func(
			toReactor v2.NextFunc,
			toConnection v2.NextFunc,
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*PublishTop5); ok {
				return NewPublishTop5Wrapper(
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})

//true
//true
//false
//false
type FullMarketDataRegisterWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *FullMarketDataRegister
}

func (self *FullMarketDataRegisterWrapper) Message() interface{} {
	return self.Data
}

func (self *FullMarketDataRegisterWrapper) messageWrapper() interface{} {
	return self
}

func NewFullMarketDataRegisterWrapper(
	toReactor v2.NextFunc,
	toConnection v2.NextFunc,
	data *FullMarketDataRegister) *FullMarketDataRegisterWrapper {
	return &FullMarketDataRegisterWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	FullMarketDataRegisterTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &FullMarketDataRegister{}
		},
		CreateWrapper: func(
			toReactor v2.NextFunc,
			toConnection v2.NextFunc,
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*FullMarketDataRegister); ok {
				return NewFullMarketDataRegisterWrapper(
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})

//true
//true
//false
//false
type FullMarketDataUnRegisterWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *FullMarketDataUnRegister
}

func (self *FullMarketDataUnRegisterWrapper) Message() interface{} {
	return self.Data
}

func (self *FullMarketDataUnRegisterWrapper) messageWrapper() interface{} {
	return self
}

func NewFullMarketDataUnRegisterWrapper(
	toReactor v2.NextFunc,
	toConnection v2.NextFunc,
	data *FullMarketDataUnRegister) *FullMarketDataUnRegisterWrapper {
	return &FullMarketDataUnRegisterWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(
			toReactor,
			toConnection),
		Data: data,
	}
}

var _ = stream.Register(
	FullMarketDataUnRegisterTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &FullMarketDataUnRegister{}
		},
		CreateWrapper: func(
			toReactor v2.NextFunc,
			toConnection v2.NextFunc,
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*FullMarketDataUnRegister); ok {
				return NewFullMarketDataUnRegisterWrapper(
					toReactor,
					toConnection,
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})
