// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v3.12.3
// source: kraken/kraken.proto

package stream

import (
	stream "github.com/bhbosman/gocommon/stream"
	goerrors "github.com/bhbosman/goerrors"
	goprotoextra "github.com/bhbosman/goprotoextra"
	proto "google.golang.org/protobuf/proto"
)

// TypeCode generated from: "Price"
const PriceTypeCode uint32 = 185142749

// true
// true
// false
// false
type PriceWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *Price
}

func (self *PriceWrapper) Message() interface{} {
	return self.Data
}

func (self *PriceWrapper) messageWrapper() interface{} {
	return self
}

func NewPriceWrapper(
	data *Price) *PriceWrapper {
	return &PriceWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(),
		Data:               data,
	}
}

var _ = stream.Register(
	PriceTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &Price{}
		},
		CreateWrapper: func(
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*Price); ok {
				return NewPriceWrapper(
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})

func (self *Price) TypeCode() uint32 {
	return PriceTypeCode
}
